[package]
name = "parse_click_data"
version = "0.1.0"
authors = ["Paul English <paul@onfrst.com>"]

[dependencies]
flate2 = "0.2"
glob = "0.2.11"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
nom = "3.2.0"
time = "0.1.38"
